# Generated by Django 6.0.7 on 2026-09-24 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва посту')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('post_type', models.CharField(choices=[('event', 'Подія'), ('science', 'Науково-дослідницька діяльність'), ('sport', 'Спортивна діяльність'), ('civic', 'Громадська діяльність'), ('art', 'Творча діяльність')], default='event', max_length=50, verbose_name='Тип посту')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='Участь у заході.', verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('status', models.BooleanField(default=False, verbose_name='Підтверджено')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('post_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='users.postattendance')),
            ],
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='users.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Зображення')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.post')),
            ],
        ),
    ]
